/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package application;

import javax.swing.JOptionPane;

/**
 *
 * @author Raza
 */
public class AdminLogin extends javax.swing.JFrame {

    /**
     * Creates new form AdminFrame
     */
    public AdminLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pwd = new javax.swing.JLabel();
        uname = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        txtPwd = new javax.swing.JPasswordField();
        loginBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        showPwd = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pwd.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        pwd.setText("Password");
        getContentPane().add(pwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 189, 124, -1));

        uname.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        uname.setText("Username");
        getContentPane().add(uname, new org.netbeans.lib.awtextra.AbsoluteConstraints(382, 106, 124, -1));
        getContentPane().add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(339, 149, 185, -1));
        getContentPane().add(txtPwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(339, 230, 188, -1));

        loginBtn.setText("Login");
        loginBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginBtnMouseClicked(evt);
            }
        });
        getContentPane().add(loginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(286, 382, -1, -1));

        backBtn.setText("Back");
        backBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backBtnMouseClicked(evt);
            }
        });
        getContentPane().add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(469, 382, -1, -1));

        showPwd.setText("Show Password");
        showPwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPwdActionPerformed(evt);
            }
        });
        getContentPane().add(showPwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 280, 141, 42));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtnMouseClicked
        int uFlag=0, pFlag=0;
        if(txtUser.getText().equals("hasnain_memon")){
            uFlag=1;
        }
        if(txtPwd.getText().equals("123098")){
            pFlag=1;
        }
        
        if(uFlag==1&&pFlag==1){
            JOptionPane.showMessageDialog(this,"Login successfully");
        }
        else if(uFlag==1&&pFlag==0){
            JOptionPane.showMessageDialog(this,"Incorrect password!");
        }
        else if(uFlag==0&&pFlag==1){
            JOptionPane.showMessageDialog(this,"Incorrect username!");
        }
        else if(uFlag==0&&pFlag==0){
            JOptionPane.showMessageDialog(this,"Incorrect username and password!");
        }        
    }//GEN-LAST:event_loginBtnMouseClicked

    private void backBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBtnMouseClicked
        setVisible(false);
        new HomePage().setVisible(true);
    }//GEN-LAST:event_backBtnMouseClicked

    private void showPwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPwdActionPerformed
        if(showPwd.isSelected()){
            txtPwd.setEchoChar((char)0);
        }else{
            txtPwd.setEchoChar('*');
        }
    }//GEN-LAST:event_showPwdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton loginBtn;
    private javax.swing.JLabel pwd;
    private javax.swing.JCheckBox showPwd;
    private javax.swing.JPasswordField txtPwd;
    private javax.swing.JTextField txtUser;
    private javax.swing.JLabel uname;
    // End of variables declaration//GEN-END:variables
}
